### ISSUE TITLE
terms linked from CLA form is a 404

### ISSUE THREAD

**Issue by dmah42** [aurae-runtime/community#4]
the CLA signing form has a link to the terms at https://github.com/aurae-runtime/authz/blob/main/TERMS.md but this is a 404.

i think authz got shuffled into authx but i can't see the TERMS.md anywhere obvious there.

**Comment by krisnova** [comment]
I've updated the google form.

Here they are: https://github.com/aurae-runtime/community/blob/main/CONTRIBUTOR_LICENSE_AGREEMENT.md#contributor-license-agreement-terms
